export const custManStyles = {
    container: {
        backgroundColor: "#ffffff",
        padding: "20px",
        borderRadius: "10px",
        boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
        width: "80%",
        maxWidth: "1000px",
        margin: "50px auto",
        textAlign: "center",
    },
    header: {
        color: "#333",
        marginBottom: "20px",
    },
    addButton: {
        backgroundColor: "#007bff",
        color: "white",
        border: "none",
        padding: "10px 20px",
        borderRadius: "5px",
        cursor: "pointer",
        marginBottom: "20px",
        transition: "background-color 0.3s ease",
    },
    table: {
        width: "100%",
        borderCollapse: "collapse",
        marginBottom: "20px",
    },
    th: {
        backgroundColor: "#007bff",
        color: "white",
        padding: "12px",
        textAlign: "left",
        borderRight: "1px solid #ddd",
    },
    td: {
        padding: "12px",
        textAlign: "left",
        borderBottom: "1px solid #ddd",
        borderRight: "1px solid #ddd",
    },
    button: {
        backgroundColor: "#007bff",
        color: "white",
        border: "none",
        padding: "8px 12px",
        borderRadius: "5px",
        cursor: "pointer",
        transition: "background-color 0.3s ease",
    },
    disabledButton: {
        backgroundColor: "#cccccc",
        cursor: "not-allowed",
    },
    updateButton: {
        backgroundColor: "#28a745",
        color: "white",
        border: "none",
        padding: "8px 12px",
        borderRadius: "5px",
        cursor: "pointer",
        transition: "background-color 0.3s ease",
    },
    deleteButton: {
        backgroundColor: "#dc3545",
        color: "white",
        border: "none",
        padding: "8px 12px",
        borderRadius: "5px",
        cursor: "pointer",
        transition: "background-color 0.3s ease",
    },
    pagination: {
        display: "flex",
        justifyContent: "center",
        gap: "10px",
        marginTop: "20px",
    }
};